services:
  keybr:
    build:
      dockerfile: ./Dockerfile
    volumes:
      - ./runtime/state:/app/state
      - ./runtime/data/.env:/app/.env
    ports:
      - 30044:3000
    restart: unless-stopped
